### PR TITLE
Better Documentation, Docker support, Github Actions, Dependabot updates

### PR DESCRIPTION
**Pull request by miguelfreitas93**
This pull request was made in order to improve the following things:
- Better Documentation:
   - Add Readme
   - Add License
   - Add Github Issues Template
- Docker Support:
   - Add Dockerfile (dependent on a previous build - target artifact should exists)
   - Add Docker-Compose
- Github Actions:
   - Automatic SAST, OSA and SCA Scans of Code User Checkmarx Github Action
- Dependabot updates:
   - Fix https://github.com/miguelfreitas93/CxCLI/pull/1
   - Fix https://github.com/miguelfreitas93/CxCLI/pull/2 
   - Fix https://github.com/miguelfreitas93/CxCLI/pull/3 
   - Fix https://github.com/miguelfreitas93/CxCLI/pull/4 
   - Fix https://github.com/miguelfreitas93/CxCLI/pull/5 
   - Fix https://github.com/miguelfreitas93/CxCLI/pull/6

### CODE REVIEW

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010353&projectid=108)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|4
Low|28
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|2

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[44](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java#L44) |Medium|Absolute_Path_Traversal|src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010353&projectid=108&pathid=17)
[211](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java#L211) |Medium|Heap_Inspection|src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010353&projectid=108&pathid=23)

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010354&projectid=108)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|4
Low|28
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|2

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[44](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java#L44) |Medium|Absolute_Path_Traversal|src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010354&projectid=108&pathid=17)
[211](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java#L211) |Medium|Heap_Inspection|src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010354&projectid=108&pathid=23)

**Comment by ghannamz** [comment]
Hi Miguel,
Please remove the LICENSE file from the PR as we need to check it with the legacy one.
Thanks!

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010374&projectid=108)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|4
Low|28
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|2

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[44](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java#L44) |Medium|Absolute_Path_Traversal|src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010374&projectid=108&pathid=17)
[211](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java#L211) |Medium|Heap_Inspection|src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010374&projectid=108&pathid=23)

**Comment by miguelfreitas93** [comment]
@ghannamz license was removed, can you please check again ? Thanks !

**Comment by ghannamz** [comment]
Scan submitted to Checkmarx

**Comment by ghannamz** [comment]
### Checkmarx scan completed
[Full Scan Details](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010384&projectid=108)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|4
Low|28
Informational|2

#### Violation Summary
Severity|Count
---|---
Medium|2

#### Details
|Lines|Severity|Category|File|Link|
---|---|---|---|---
[44](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java#L44) |Medium|Absolute_Path_Traversal|src/main/java/com/cx/plugin/cli/CxConsoleLauncher.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010384&projectid=108&pathid=17)
[211](https://github.com/checkmarx-ltd/CLI/blob/master/src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java#L211) |Medium|Heap_Inspection|src/main/java/com/cx/plugin/cli/utils/CxConfigHelper.java|[Checkmarx](http://EC2AMAZ-JP2I9QF/CxWebClient/ViewerMain.aspx?scanid=1010384&projectid=108&pathid=23)

**Pull request closed without merging**
